name: .NET

on:
  push:
    tags: 
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/sebfia/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_PUSH}}
    - name: Install paket as global tool
      run: dotnet tool install -g paket
    - name: Restore local tools
      run: dotnet tool restore
    - name: Install dependencies using paket
      run: paket install
    - name: Restore dependencies
      run: dotnet restore ./src/Client/Client.fsproj
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${VERSION} ./src/Client/Client.fsproj
    - name: Pack Nuget
      run: dotnet pack --configuration Release /p:Version=${VERSION} ./src/Client/Client.fsproj
    - name: Publish Nuget
      run: dotnet nuget push ./src/Client/bin/Release/*.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_PUSH }}
    
